export const PcColumn1 = [
  {
    title: "누구랑 모바일앱",
    href: "/detail/nugulang",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_nugulangx2-3.webp",
    imgsize: [597.33, 467],
    tags: ["UX/UI", "Mobile", "브로드베이", "커뮤니티", "2026"],
  },
  {
    title: "굿모닝페이 홈페이지",
    href: "/detail/gmpaylanding",
    tools: ["/tool_figma.webp", "/tool_html.webp"],
    imgsrc: "/thb_gmpaylandingx2-2.webp",
    imgsize: [597.33, 431],
    tags: [
      "UX/UI · Publishing",
      "Web · Tablet · Mobile",
      "코리아페이먼트",
      "금융",
      "2025",
    ],
  },
  {
    title: "씨오톡 모바일앱",
    href: "/detail/cotalk",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_cotalkx2-2.webp",
    imgsize: [597.33, 437],
    tags: ["UX/UI", "Mobile", "런인베스트", "금융", "2022"],
  },
  {
    title: "Partage",
    href: "/detail/partage",
    tools: ["/tool_figma.webp", "/tool_nextjs.webp"],
    imgsrc: "/thb_partagex2-2.webp",
    imgsize: [597.33, 420],
    tags: [
      "UX/UI · Partial Publishing",
      "Web · Tablet · Mobile",
      "콘텐츠 커뮤니티",
      "2024",
    ],
  },
];

export const PcColumn2 = [
  {
    title: "IMQA 모니터링 웹앱",
    href: "/detail/imqa",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_imqax2.webp",
    imgsize: [597.33, 417],
    tags: ["UX/UI", "Web", "어니컴", "데이터시각화", "2025"],
  },
  {
    title: "굿모닝페이 모바일앱",
    href: "/detail/gmpay",
    tools: ["/tool_figma.webp", "/tool_flutter.webp"],
    imgsrc: "/thb_gmpayx2-2.webp",
    imgsize: [597.33, 635],
    tags: ["UX/UI · Publishing", "Mobile", "코리아페이먼트", "금융", "2025"],
  },
  {
    title: "하나 스마트창구 태블릿 인터페이스",
    href: "/detail/hanasmart",
    tools: ["/tool_xd.webp", "/tool_ai.webp"],
    imgsrc: "/thb_hanasmartx2.webp",
    imgsize: [597.33, 491],
    tags: ["UI", "Tablet", "하나은행", "금융", "2025"],
  },
];

export const PcColumn3 = [
  {
    title: "IMQA 랜딩페이지",
    href: "/detail/imqalanding",
    tools: ["/tool_figma.webp", "/tool_nextjs.webp"],
    imgsrc: "/thb_imqalandingx2.webp",
    imgsize: [597.33, 535],
    tags: [
      "UX/UI · Publishing",
      "Web · Tablet · Mobile",
      "어니컴",
      "데이터시각화",
      "2026",
    ],
  },
  {
    title: "씨오파트너 웹앱",
    href: "/detail/copartner",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_copartnerx2.webp",
    imgsize: [597.33, 423],
    tags: ["UX/UI", "Web · Tablet", "런인베스트", "금융", "2023"],
  },
  {
    title: "요기거리 모바일앱",
    href: "/detail/yogi",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_yogix2-2.webp",
    imgsize: [597.33, 629],
    tags: ["UX/UI", "Mobile", "로컬커뮤니티", "2022"],
  },
];

export const TabletColumn1 = [
  {
    title: "누구랑 모바일앱",
    href: "/detail/nugulang",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_nugulangx2-2.webp",
    imgsize: [597.33, 467],
    tags: ["UX/UI", "Mobile", "브로드베이", "커뮤니티", "2026"],
  },
  {
    title: "IMQA 랜딩페이지",
    href: "/detail/imqalanding",
    tools: ["/tool_figma.webp", "/tool_nextjs.webp"],
    imgsrc: "/thb_imqalandingx2.webp",
    imgsize: [597.33, 535],
    tags: [
      "UX/UI · Publishing",
      "Web · Tablet · Mobile",
      "어니컴",
      "데이터시각화",
      "2026",
    ],
  },
  {
    title: "굿모닝페이 모바일앱",
    href: "/detail/gmpay",
    tools: ["/tool_figma.webp", "/tool_flutter.webp"],
    imgsrc: "/thb_gmpayx2-2.webp",
    imgsize: [597.33, 635],
    tags: ["UX/UI · Publishing", "Mobile", "코리아페이먼트", "금융", "2025"],
  },
  {
    title: "씨오톡 모바일앱",
    href: "/detail/cotalk",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_cotalkx2-2.webp",
    imgsize: [597.33, 437],
    tags: ["UX/UI", "Mobile", "런인베스트", "금융", "2022"],
  },
  {
    title: "요기거리 모바일앱",
    href: "/detail/yogi",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_yogix2-2.webp",
    imgsize: [597.33, 629],
    tags: ["UX/UI", "Mobile", "로컬커뮤니티", "2022"],
  },
];

export const TabletColumn2 = [
  {
    title: "IMQA 모니터링 웹앱",
    href: "/detail/imqa",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_imqax2.webp",
    imgsize: [597.33, 417],
    tags: ["UX/UI", "Web", "어니컴", "데이터시각화", "2025"],
  },
  {
    title: "굿모닝페이 홈페이지",
    href: "/detail/gmpaylanding",
    tools: ["/tool_figma.webp", "/tool_html.webp"],
    imgsrc: "/thb_gmpaylandingx2-2.webp",
    imgsize: [597.33, 431],
    tags: [
      "UX/UI · Publishing",
      "Web · Tablet · Mobile",
      "코리아페이먼트",
      "금융",
      "2025",
    ],
  },
  {
    title: "씨오파트너 웹앱",
    href: "/detail/copartner",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_copartnerx2.webp",
    imgsize: [597.33, 423],
    tags: ["UX/UI", "Web · Tablet", "런인베스트", "금융", "2023"],
  },
  {
    title: "하나 스마트창구 태블릿 인터페이스",
    href: "/detail/hanasmart",
    tools: ["/tool_xd.webp", "/tool_ai.webp"],
    imgsrc: "/thb_hanasmartx2.webp",
    imgsize: [597.33, 491],
    tags: ["UI", "Tablet", "하나은행", "금융", "2025"],
  },
  {
    title: "Partage",
    href: "/detail/partage",
    tools: ["/tool_figma.webp", "/tool_nextjs.webp"],
    imgsrc: "/thb_partagex2-2.webp",
    imgsize: [597.33, 420],
    tags: [
      "UX/UI · Partial Publishing",
      "Web · Tablet · Mobile",
      "콘텐츠 커뮤니티",
      "2024",
    ],
  },
];

export const MobileColumn = [
  {
    title: "누구랑 모바일앱",
    href: "/detail/nugulang",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_nugulangx2-2.webp",
    imgsize: [597.33, 467],
    tags: ["UX/UI", "Mobile", "브로드베이", "커뮤니티", "2026"],
  },

  {
    title: "IMQA 모니터링 웹앱",
    href: "/detail/imqa",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_imqax2.webp",
    imgsize: [597.33, 417],
    tags: ["UX/UI", "Web", "어니컴", "데이터시각화", "2025"],
  },
  {
    title: "IMQA 랜딩페이지",
    href: "/detail/imqalanding",
    tools: ["/tool_figma.webp", "/tool_nextjs.webp"],
    imgsrc: "/thb_imqalandingx2.webp",
    imgsize: [597.33, 535],
    tags: [
      "UX/UI · Publishing",
      "Web · Tablet · Mobile",
      "어니컴",
      "데이터시각화",
      "2026",
    ],
  },
  {
    title: "굿모닝페이 홈페이지",
    href: "/detail/gmpaylanding",
    tools: ["/tool_figma.webp", "/tool_html.webp"],
    imgsrc: "/thb_gmpaylandingx2-2.webp",
    imgsize: [597.33, 431],
    tags: [
      "UX/UI · Publishing",
      "Web · Tablet · Mobile",
      "코리아페이먼트",
      "금융",
      "2025",
    ],
  },
  {
    title: "굿모닝페이 모바일앱",
    href: "/detail/gmpay",
    tools: ["/tool_figma.webp", "/tool_flutter.webp"],
    imgsrc: "/thb_gmpayx2-2.webp",
    imgsize: [597.33, 635],
    tags: ["UX/UI · Publishing", "Mobile", "코리아페이먼트", "금융", "2025"],
  },
  {
    title: "씨오파트너 웹앱",
    href: "/detail/copartner",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_copartnerx2.webp",
    imgsize: [597.33, 423],
    tags: ["UX/UI", "Web · Tablet", "런인베스트", "금융", "2023"],
  },

  {
    title: "씨오톡 모바일앱",
    href: "/detail/cotalk",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_cotalkx2-2.webp",
    imgsize: [597.33, 437],
    tags: ["UX/UI", "Mobile", "런인베스트", "금융", "2022"],
  },
  {
    title: "하나 스마트창구 태블릿 인터페이스",
    href: "/detail/hanasmart",
    tools: ["/tool_xd.webp", "/tool_ai.webp"],
    imgsrc: "/thb_hanasmartx2.webp",
    imgsize: [597.33, 491],
    tags: ["UI", "Tablet", "하나은행", "금융", "2025"],
  },
  {
    title: "요기거리 모바일앱",
    href: "/detail/yogi",
    tools: ["/tool_figma.webp"],
    imgsrc: "/thb_yogix2-2.webp",
    imgsize: [597.33, 629],
    tags: ["UX/UI", "Mobile", "로컬커뮤니티", "2022"],
  },
  {
    title: "Partage",
    href: "/detail/partage",
    tools: ["/tool_figma.webp", "/tool_nextjs.webp"],
    imgsrc: "/thb_partagex2-2.webp",
    imgsize: [597.33, 420],
    tags: [
      "UX/UI · Partial Publishing",
      "Web · Tablet · Mobile",
      "콘텐츠 커뮤니티",
      "2024",
    ],
  },
];
